#lang scheme
(define (make-account balance password)
  (define secure-count 0)
  (define (call-the-cops x)
    "Attempted breakin detected, calling the police")
  (define (password? x)
    (eq? x password))
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch pw m)
    (cond ((> secure-count 7) call-the-cops)
          ((not (password? pw)) (set! secure-count (+ secure-count 1))
                                (lambda (x) "Incorrect password"))
          ((eq? m 'withdraw) (set! secure-count 0)
                             withdraw)
          ((eq? m 'deposit) (set! secure-count 0)
                            deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       m))))
  dispatch)